In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/store-sales-time-series-forecasting/oil.csv
/kaggle/input/competitions/store-sales-time-series-forecasting/sample_submission.csv
/kaggle/input/competitions/store-sales-time-series-forecasting/holidays_events.csv
/kaggle/input/competitions/store-sales-time-series-forecasting/stores.csv
/kaggle/input/competitions/store-sales-time-series-forecasting/train.csv
/kaggle/input/competitions/store-sales-time-series-forecasting/test.csv
/kaggle/input/competitions/store-sales-time-series-forecasting/transactions.csv

In [3]:
import os 

path = '/kaggle/input/competitions/store-sales-time-series-forecasting/'

train = pd.read_csv( path + 'train.csv', parse_dates = ['date'])
stores = pd.read_csv(path + 'stores.csv')
oil = pd.read_csv(path + 'oil.csv', parse_dates = ['date'])

In [4]:
print(train.head())
print(stores.head())
oil.head(10)

   id       date  store_nbr      family  sales  onpromotion
0   0 2013-01-01          1  AUTOMOTIVE    0.0            0
1   1 2013-01-01          1   BABY CARE    0.0            0
2   2 2013-01-01          1      BEAUTY    0.0            0
3   3 2013-01-01          1   BEVERAGES    0.0            0
4   4 2013-01-01          1       BOOKS    0.0            0
   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

        date  dcoilwtico
0 2013-01-01         NaN
1 2013-01-02       93.14
2 2013-01-03       92.97
3 2013-01-04       93.12
4 2013-01-07       93.20
5 2013-01-08       93.21
6 2013-01-09       93.08
7 2013-01-10       93.81
8 2013-01-11       93.60
9 2013-01-14       94.27

In [5]:
oil = oil.set_index('date').resample('D').interpolate(method= 'linear').reset_index()
oil.head(10)

        date  dcoilwtico
0 2013-01-01         NaN
1 2013-01-02   93.140000
2 2013-01-03   92.970000
3 2013-01-04   93.120000
4 2013-01-05   93.146667
5 2013-01-06   93.173333
6 2013-01-07   93.200000
7 2013-01-08   93.210000
8 2013-01-09   93.080000
9 2013-01-10   93.810000

In [6]:
print(train.shape)
stores.shape

(3000888, 6)

(54, 5)

In [10]:
df = train.merge(stores, on = 'store_nbr', how ='left')
df = df.merge(oil, on = 'date', how='left')
print(f"Forma del dataset unido: {df.shape}")
print(f"Valores nulos después del merge:\n{df.isnull().sum()}")
df.head()

Forma del dataset unido: (3000888, 11)
Valores nulos después del merge:
id                0
date              0
store_nbr         0
family            0
sales             0
onpromotion       0
city              0
state             0
type              0
cluster           0
dcoilwtico     1782
dtype: int64

,id,date,store_nbr,family,sales,onpromotion,city,state,type,cluster,dcoilwtico
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,NaN
1,1,2013-01-01,1,BABY CARE,0.0,0,Quito,Pichincha,D,13,NaN
2,2,2013-01-01,1,BEAUTY,0.0,0,Quito,Pichincha,D,13,NaN
3,3,2013-01-01,1,BEVERAGES,0.0,0,Quito,Pichincha,D,13,NaN
4,4,2013-01-01,1,BOOKS,0.0,0,Quito,Pichincha,D,13,NaN